language: rust
rust:
  - stable
  # - beta
  # - nightly
os:
  - linux
  - osx
  - windows
matrix:
  #   - rust: stable
  #   - rust: beta
  allow_failures:
    - os: windows
  fast_finish: true
before_script:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
script:
  - cargo fmt --all -- --check
  - cargo clippy --all -- -D clippy::pedantic -D clippy::nursery -D warnings
  - cargo build --release
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then chmod +x target/release/cur.exe ; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then chmod +x target/release/cur ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then gzip -k -f target/release/cur.exe ; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then gzip -k -f target/release/cur ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv target/release/cur.gz cur_linux.gz ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mv target/release/cur.gz cur_osx.gz ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then mv target/release/cur.exe.gz cur_windows.gz ; fi
deploy:
  - provider: releases
    api_key: $gh_key
    file:
      - cur_linux.gz
      - cur_osx.gz
      - cur_windows.gz
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: bash .travis/deploy.sh
    skip_cleanup: true
    on:
      tags: true
