name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
#  test:
#    name: ${{ matrix.rust }} on ${{ matrix.os }}
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        rust: [stable]
#        os: [ubuntu-latest, macOS-latest, windows-latest]
#    steps:
#      - uses: hecrj/setup-rust-action@master
#        with:
#          rust-version: ${{ matrix.rust }}
#      - uses: actions/checkout@v1
#      - name: Install components
#        run: |
#          rustup component add rustfmt
#          rustup component add clippy
#      - name: Run cargo fmt
#        run: cargo fmt --all -- --check
#      - name: Run cargo clippy
#        run: cargo clippy --all -- -D clippy::pedantic -D clippy::nursery -D warnings
#      - name: Run tests
#        run: cargo test --verbose
  build:
#    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable]
        os: [ubuntu-latest]
    steps:
      - uses: hecrj/setup-rust-action@master
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@v1
      - name: Build the crate for release
        # if: startsWith(github.ref, 'refs/tags/v')
        run: cargo build --release
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@master
        with:
          rust-version: stable
      - uses: actions/checkout@v1
#      - name: Build the crate for release
##          if: startsWith(github.ref, 'refs/tags/v')
#          run: cargo build --release
      - name: Permissions on executables Unix
##          if: startsWith(github.ref, 'refs/tags/v') && matrix.os  != 'windows-latest'
          run: chmod +x ./target/release/cur
##      - name: Permissions on executables Windows
##          if: startsWith(github.ref, 'refs/tags/v') && ${{ matrix.os }} == 'windows-latest'
##          run: chmod +x ./target/release/cur.exe
      - name: Zip artifacts for Unix
          uses: juankaram/archive-action@v1.0.0
#          if: startsWith(github.ref, 'refs/tags/v') && ${{ matrix.os }} != 'windows-latest'
          with:
            args: zip -r cur.zip ./target/release/cur
##      - name: Zip artifacts for Windows
##          uses: juankaram/archive-action@v1.0.0
##          if: startsWith(github.ref, 'refs/tags/v') && ${{ matrix.os }} == 'windows-latest'
##          with:
##            args: zip -r deployment_artifact.zip ./target/release/cur.exe
#      - name: GitHub Release
#          uses: docker://softprops/action-gh-release
#          if: startsWith(github.ref, 'refs/tags/v')
#          with:
#            files:
#              - cur_linux.zip
#              - cur_osx.zip
#              - cur_windows.zip
#          env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
